services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  MFR\T3PromClient\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'

  MFR\T3PromClient\Middleware\PrometheusMiddleware:
    arguments:
      $responseFactory: '@Psr\Http\Message\ResponseFactoryInterface'
      $streamFactory: '@Psr\Http\Message\StreamFactoryInterface'

  TYPO3\CMS\Install\Report\EnvironmentStatusReport:
    public: true
  
  TYPO3\CMS\Install\Report\InstallStatusReport:
    public: true

  MFR\T3PromClient\Service\PrometheusService:
    arguments:
      $environmentStatusReport: '@TYPO3\CMS\Install\Report\EnvironmentStatusReport'
      $installStatusReport: '@TYPO3\CMS\Install\Report\InstallStatusReport'