services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  MFR\Typo3Prometheus\Middleware\PrometheusMiddleware:
    arguments:
      $responseFactory: '@Psr\Http\Message\ResponseFactoryInterface'
      $streamFactory: '@Psr\Http\Message\StreamFactoryInterface'