services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  MFR\T3PromClient\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'

  MFR\T3PromClient\Middleware\PrometheusMiddleware:
    arguments:
      $responseFactory: '@Psr\Http\Message\ResponseFactoryInterface'
      $streamFactory: '@Psr\Http\Message\StreamFactoryInterface'

  MFR\T3PromClient\Registry\MetricRegistry:
    arguments:
      - !tagged_iterator prometheus.metric